name: Vue.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-type-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x' 
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run type checks
      run: npm run type-check

    - name: Build the project
      run: npm run build
