name: Deploy Vue.js to GitHub Pages

on:
  push:
    branches: [main]  # Run this action on push events to the main branch
  workflow_dispatch:  # Allow manual triggers from the GitHub Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Checkout the repository content

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the node version compatible with your project

    - name: Install Dependencies
      run: npm install  # Install npm dependencies

    - name: Build
      run: npm run build  # Build the Vue project, output to dist/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  

