name: Deploy Vue.js to GitHub Branch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Branch
        run: |
          git checkout --orphan github-page
          git reset --hard
          git add -f dist
          git mv dist/* .
          git clean -fdx
          git commit -m "Deploy to github-page branch"
          git push -f origin HEAD:github-page
