name: Deploy Vue.js to GitHub Branch

on:
  push:
    branches: [main]
  workflow_dispatch:  

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: npm install 

      - name: Build
        run: npm run build 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push to github-page Branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b github-page
          git add dist
          git commit -m "Deploy to github-page branch"
          git subtree split --prefix dist -b github-page
          git push -f origin github-page:github-page
